#!/bin/bash
cd /home/ec2-user/node-js-app

. ~/.nvm/nvm.sh

npm i -g @nestjs/cli typescript ts-node
npm i

# include aws functions
source ./scripts/aws.sh

env_stage=$(cat /root/.env-stage)

# when production
if [[ $env_stage = "prod" ]]
then
    init_aws_env

    sh ./scripts/production.sh
fi

# when release candidate
if [[ $env_stage = "release" ]]
then
    init_aws_env

    sh ./scripts/release-candidate.sh
fi

# when development
if [[ $env_stage = "dev" ]]
then
    init_aws_env

    sh ./scripts/development.sh
fi
