version: 0.2

phases:
  install:
    commands:
      - cd $CODEBUILD_SRC_DIR;
      - npm install -g env-cmd
      - npm i
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR;
      - env-cmd -f .env.$APP_ENV ./node_modules/.bin/gatsby build --prefix-paths
artifacts:
  base-directory: public
  files:
    - ./**/*
