version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/node-js-app
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 600
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/cleanup.sh
      runas: root
