#!/bin/bash

source /etc/profile.d/rvm.sh
cd /home/ec2-user/ruby-on-rails

if [[ $DEPLOYMENT_GROUP_NAME = *"-EnvWebApp"* ]]
then
    if [[ <%= use_worker %> = true ]]
    then
        worker_ip=$(aws ssm get-parameters --region us-west-2 --names <%= application_name %>-WorkerAppIpSSM  --with-decryption --query Parameters[0].Value)
        worker_ip=`echo $worker_ip | sed -e 's/^"//' -e 's/"$//'`

        export REDIS_URL=redis://$worker_ip\:6379
    fi

    bundle exec puma -C config/puma_production.rb
fi

if [[ $DEPLOYMENT_GROUP_NAME = *"-WorkerApp"* ]]
then
    # ensure redis is run as deamon
    sed -i -- '0,/daemonize no/s/daemonize no/daemonize yes/' /etc/redis.conf
    # Start redis
    redis-server /etc/redis.conf
    # start sidekiq -t 60 - time pause for stop process
    bundle exec sidekiq -d -L log/sidekiq.log -C config/sidekiq.yml -P tmp/sidekiq.pid -e production -t 60
fi
