#!/bin/bash
cd /home/ec2-user/ruby-on-rails
mkdir -p log

. ~/.nvm/nvm.sh # for assets, maybe ruby active admin
source /etc/profile.d/rvm.sh
rvm list
rvm gemset list
gem list

app_name='<%= application_name %>'
app_region='us-west-2'
worker_is_enabled=<%= use_worker %>

get_ssm_param() {
    param_name=$1
    value=$(aws ssm get-parameters --region ${app_region} --names ${app_name}-${param_name} --with-decryption --query Parameters[0].Value)
    echo $value | sed -e 's/^"//' -e 's/"$//'
}

db_name=$(get_ssm_param "db-name")
db_user=$(get_ssm_param "db-user")
db_password=$(get_ssm_param "db-password")
db_host=$(get_ssm_param "db-host")
carier_wave_s3_bucket=$(get_ssm_param "CarierWaveS3BucketNameSSM")
user_access_key=$(get_ssm_param "IAMStackUserAccessKeySSM")
user_secret_access_key=$(get_ssm_param "IAMStackUserSecretAccessKeySSM")

[ -f .env ] && rm .env || echo .env is not exists yet

echo DATABASE=$db_name >> .env
echo DATABASE_USERNAME=$db_user >> .env
echo DATABASE_PASSWORD=$db_password >> .env
echo DATABASE_HOST=$db_host >> .env
echo RAILS_ENV=production >> .env
echo RAKE_ENV=production >> .env
echo DEVISE_SECRET=8db1b8d5158b97eb7b54bf002765323c04a5c1be86d34b44548637f6e7a358e160a078390957e5481b069761e8b8c1dcd0489cb0fa2ab302071d878634878161 >> .env
echo DAEMONIZE_PUMA=true >> .env
echo PORT=80 >> .env
echo AWS_ACCESS_KEY_ID=$user_access_key >> .env
echo AWS_SECRET_ACCESS_KEY=$user_secret_access_key >> .env
echo AWS_DEFAULT_S3_BUCKET=$carier_wave_s3_bucket >> .env
echo AWS_S3_REGION=$app_region >> .env

if [[ $DEPLOYMENT_GROUP_NAME = *"-WebApp"* ]] && [[ $worker_is_enabled = true ]]
then
    worker_ip=$(get_ssm_param "WorkerAppIpSSM")

    echo REDIS_URL=redis://$worker_ip\:6379 >> .env
fi

echo Copy project specific variables to .env
cat .env.custom >> .env

#rvm requirements
#rvm install 2.3.3

gem install bundler -v 1.17.0
bundle install --without development test

export SECRET_KEY_BASE="$(bundle exec rake secret)"
