#!/bin/bash

source /etc/profile.d/rvm.sh
cd /home/ec2-user/ruby-on-rails

if [[ $DEPLOYMENT_GROUP_NAME = *"-EnvWebApp"* ]]
then
    bundle exec puma -C config/puma_production.rb
fi

if [[ $DEPLOYMENT_GROUP_NAME = *"-WorkerApp"* ]]
then
    # Start redis
    redis-server /etc/redis.conf
    # start sidekiq -t 60 - time pause for stop process
    bundle exec sidekiq -d -L log/sidekiq.log -C config/sidekiq.yml -P tmp/sidekiq.pid -e production -t 60
fi
