#!/bin/bash

. ~/.nvm/nvm.sh

if [[ $DEPLOYMENT_GROUP_NAME = *"WebApp"* ]]
then
    pm2 delete <%= application_name %> || echo no running instance of <%= application_name %>
fi

if [[ $DEPLOYMENT_GROUP_NAME = *"WorkerApp"* ]]
then
    echo TODO:implementStopCommandWorker
#    pm2 delete <%= application_name %>-worker || echo no running instance of <%= application_name %>-worker
fi


exit 0
