#!/bin/bash
cd /home/ec2-user/node-js-app

. ~/.nvm/nvm.sh

# include aws functions
source ./aws.sh

# when production
if [[ $DEPLOYMENT_GROUP_NAME = *"prod"* ]]
then
    app_name='<%= applicationName %>'
    app_region='us-west-2'
    prefix='prod'

    init_aws_env

    sh ./scripts/production.sh ${app_region} ${app_name} ${prefix}
fi

# when release candidate
if [[ $DEPLOYMENT_GROUP_NAME = *"release"* ]]
then
    app_name='<%= applicationName %>'
    app_region='us-west-2'
    prefix='release'

    init_aws_env

    sh ./scripts/release-candidate.sh ${app_region} ${app_name} ${prefix}
fi

# when development
if [[ $DEPLOYMENT_GROUP_NAME = *"dev"* ]]
then
    app_name='<%= applicationName %>'
    app_region='us-west-2'
    prefix='dev'

    init_aws_env

    sh ./scripts/development.sh ${app_region} ${app_name} ${prefix}
fi
