#!/bin/bash

. ~/.nvm/nvm.sh

app_name='<%= applicationName %>'

stop() {
    if [[ $DEPLOYMENT_GROUP_NAME = *"WebApp"* ]]
    then
        pm2 delete $app_name || echo no running instance of $app_name
    fi

    if [[ $DEPLOYMENT_GROUP_NAME = *"WorkerApp"* ]]
    then
        echo TODO:implementStopCommandWorker
    #    pm2 delete $app_name-worker || echo no running instance of $app_name-worker
    fi
}

productionStop() {
    # you can implement custom stop any services
    stop
}

releaseCandidateStop() {
    # you can implement custom stop any services
    stop
}

developmentStop() {
    # you can implement custom stop any services
    stop
}

if [[ $DEPLOYMENT_GROUP_NAME = *"production"* ]]
then
    productionStop
fi


if [[ $DEPLOYMENT_GROUP_NAME = *"release"* ]]
then
    releaseCandidateStop
fi

if [[ $DEPLOYMENT_GROUP_NAME = *"dev"* ]]
then
    developmentStop
fi
