version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/ruby-on-rails
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 400
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/arrange-deployment-folders.sh
      runas: root
