#!/bin/bash
cd /home/ec2-user/node-js-app
mkdir -p log

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

npm i -g @nestjs/cli typescript ts-node
npm i

db_name=$(aws ssm get-parameters --region us-west-2 --names <%= application_name %>-db-name  --with-decryption --query Parameters[0].Value)
db_name=`echo $db_name | sed -e 's/^"//' -e 's/"$//'`

db_user=$(aws ssm get-parameters --region us-west-2 --names <%= application_name %>-db-user  --with-decryption --query Parameters[0].Value)
db_user=`echo $db_user | sed -e 's/^"//' -e 's/"$//'`

db_password=$(aws ssm get-parameters --region us-west-2 --names <%= application_name %>-db-password  --with-decryption --query Parameters[0].Value)
db_password=`echo $db_password | sed -e 's/^"//' -e 's/"$//'`

db_host=$(aws ssm get-parameters --region us-west-2 --names <%= application_name %>-db-host  --with-decryption --query Parameters[0].Value)
db_host=`echo $db_host | sed -e 's/^"//' -e 's/"$//'`

#carier_wave_s3_bucket=$(aws ssm get-parameters --region us-west-2 --names <%= application_name %>-CarierWaveS3BucketNameSSM  --with-decryption --query Parameters[0].Value)
#carier_wave_s3_bucket=`echo $carier_wave_s3_bucket | sed -e 's/^"//' -e 's/"$//'`

user_access_key=$(aws ssm get-parameters --region us-west-2 --names <%= application_name %>-IAMStackUserAccessKeySSM  --with-decryption --query Parameters[0].Value)
user_access_key=`echo $user_access_key | sed -e 's/^"//' -e 's/"$//'`

user_secret_access_key=$(aws ssm get-parameters --region us-west-2 --names <%= application_name %>-IAMStackUserSecretAccessKeySSM  --with-decryption --query Parameters[0].Value)
user_secret_access_key=`echo $user_secret_access_key | sed -e 's/^"//' -e 's/"$//'`

[ -f production.env ] && rm production.env || echo production.env is not exists yet

echo DATABASE_NAME=$db_name >> production.env
echo DATABASE_USERNAME=$db_user >> production.env
echo DATABASE_PASSWORD=$db_password >> production.env
echo DATABASE_HOST=$db_host >> production.env
echo NODE_ENV=production >> production.env
echo TOKEN_EXPIRATION_HOUR=24 >> production.env
echo DATABASE_SYNCHRONIZE=false >> production.env
echo AUTH_JWT_SECRET=8db1b8d5158b97eb7b54bf002765323c04a5c1be86d34b44548637f6e7a358e160a078390957e5481b069761e8b8c1dcd0489cb0fa2ab302071d878634878161 >> production.env
echo API_PREFIX=api/v1 >> production.env
echo AUTH_JWT_TOKEN_EXPIRES_IN=3600 >> production.env
echo DATABASE_PORT=5432 >> production.env
echo DATABASE_TYPE=<%= database_type %> >> production.env


echo Copy project specific variables to production.env
cat .env.custom >> production.env

npm run prestart:prod
pm2 start npm --no-automation --name <%= application_name %> -- run start:prod
