version: 0.2
phases:
  install:
    runtime-versions:
#      nodejs: 12
    commands:
#      - yarn install
#      - export CYPRESS_BASE_URL=$RELEASE_URL
  pre_build:
    commands:
#      - rm -R -f report && mkdir report
  build:
    commands:
#      - yarn cypress run --headless --browser firefox
  post_build:
    commands:
#      - node mergeReports.js
#      - yarn marge ./report/mochawesome-report/report.json -f index -o report
#      - aws s3 cp --acl $REPORT_ACL --recursive ./report s3://$BUILD_OUTPUT_BUCKET/report-$REPORT_UUID
