version: 0.2

#env:
#  variables:
#     ENV_NAME: VALUE

phases:
  install:
    # https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html
    runtime-version:
      nodejs: 12.x
    commands:
      - cd $CODEBUILD_SRC_DIR;
      - npm install -g typescript
      - npm install aws-sdk --save
      - npm i
      - cd $CODEBUILD_SRC_DIR/s3-deployment-custom-resource; npm install
      - cd ../
  pre_build:
    commands:
    #- cd $CODEBUILD_SRC_DIR; node configure.js $STAGE
  build:
    commands:
      # add to package json "build" command
      - cd $CODEBUILD_SRC_DIR; npm run build
  post_build:
    commands:
      # you can change build directory to custom
      - cd $CODEBUILD_SRC_DIR/build; zip -r ../package.zip *
      - cd ../
      - aws cloudformation package --template-file app-sam.yml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file app-output_sam.yaml
artifacts:
  files:
    - app-output_sam.yaml
    - package.zip
  discard-paths: yes
