#!/bin/bash
cd /home/ec2-user/ruby-on-rails

mkdir -p /var/log/rails
mkdir -p /tmp/rails

ln -s /var/log/rails /home/ec2-user/ruby-on-rails/log
ln -s /tmp/rails /home/ec2-user/ruby-on-rails/tmp

. ~/.nvm/nvm.sh # for assets, maybe ruby active admin
source /etc/profile.d/rvm.sh
rvm list
rvm gemset list
gem list

# include aws functions
source ./aws.sh

# when production
if [[ $DEPLOYMENT_GROUP_NAME = *"prod"* ]]
then
    app_name='<%= applicationName %>'
    app_region='us-west-2'
    prefix='prod'

    init_aws_env

    sh ./scripts/production.sh ${app_region} ${app_name}
fi

# when release candidate
if [[ $DEPLOYMENT_GROUP_NAME = *"release"* ]]
then
    app_name='<%= applicationName %>'
    app_region='us-west-2'
    prefix='release'

    init_aws_env

    sh ./scripts/release-candidate.sh ${app_region} ${app_name}
fi

# when development
if [[ $DEPLOYMENT_GROUP_NAME = *"dev"* ]]
then
    app_name='<%= applicationName %>'
    app_region='us-west-2'
    prefix='dev'

    init_aws_env

    sh ./scripts/development.sh ${app_region} ${app_name}
fi

