#!/bin/bash

stop() {
    if [[ $DEPLOYMENT_GROUP_NAME = *"WebApp"* ]]
    then
        if lsof -t -i:80 > /dev/null
            then
                kill -9 $(lsof -t -i:80)
            else
                echo Nothing running on port 80
        fi
    fi

    if [[ $DEPLOYMENT_GROUP_NAME = *"WorkerApp"* ]]
    then
        [ -f /home/ec2-user/ruby-on-rails/tmp/sidekiq.pid ] && cat /home/ec2-user/ruby-on-rails/tmp/sidekiq.pid | xargs kill -TERM || echo "No running sidekiq pid found"
    fi
}

productionStop() {
    # you can implement custom stop any services
    stop
}

releaseCandidateStop() {
    # you can implement custom stop any services
    stop
}

developmentStop() {
    # you can implement custom stop any services
    stop
}

if [[ $DEPLOYMENT_GROUP_NAME = *"production"* ]]
then
    productionStop
fi


if [[ $DEPLOYMENT_GROUP_NAME = *"release"* ]]
then
    releaseCandidateStop
fi

if [[ $DEPLOYMENT_GROUP_NAME = *"dev"* ]]
then
    developmentStop
fi
