version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 600
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/cleanup.sh
      runas: ec2-user
